### ISSUE TITLE
loghub 0.5.0 causes UndefinedError for old workflow

### ISSUE THREAD

**Issue by djhoese** [spyder-ide/loghub#119]
I've been using loghub for a while now and with a recent update from a master-branch based installation (~0.5.0) to the released 0.5.0 version I now get:

```
$ loghub pytroll/pycoast -t "$LOGHUB_GITHUB_TOKEN" -st v1.3.2 -plg bug "Bugs fixed" -plg enhancement "Features added" -plg documentation "Documentation changes"

LOGHUB: Querying issues since tag "v1.3.2"

Traceback (most recent call last):
  File "/home/davidh/miniconda3/envs/satpy_py37/bin/loghub", line 8, in <module>
    sys.exit(main())
  File "/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/loghub/cli/main.py", line 52, in main
    parse_arguments(skip=False)
  File "/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/loghub/cli/main.py", line 299, in parse_arguments
    show_related_issues=options.show_related_issues,
  File "/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/loghub/core/formatter.py", line 381, in create_changelog
    show_prs=show_prs)
  File "/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/loghub/core/formatter.py", line 453, in render_changelog
    show_prs=show_prs)
  File "/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 25, in top-level template code
  File "/home/davidh/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'pri' is undefined
```

What can I do to fix this?

NOTE: This works with 0.4.0.

**Comment by goanpeca** [comment]
Hi @djhoese, sorry for the issues. I will take a look at this, this week. Will try your example and see if I can reproduce it ok?

Cheers!

**Comment by djhoese** [comment]
Any updates on this? I'm not really up to date on the recent changes to loghub so I'm not sure if I can help.

**Comment by ccordoba12** [comment]
@goanpeca, please take a look at this one.

**Comment by goanpeca** [comment]
I cannot reproduce this issue, so I am not sure where the error is coming from.

**Comment by djhoese** [comment]
With conda-forge channel added as priority and strict channel priority set:

```
conda create -n loghub_test python=3.7 loghub
conda activate loghub_test
loghub pytroll/pycoast -t "$LOGHUB_GITHUB_TOKEN" -st v1.3.2 -plg bug "Bugs fixed" -plg enhancement "Features added" -plg documentation "Documentation changes"

LOGHUB: Querying issues since tag "v1.3.2"

Traceback (most recent call last):
  File "/home/davidh/miniconda3/envs/loghub_test/bin/loghub", line 10, in <module>
    sys.exit(main())
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/loghub/cli/main.py", line 52, in main
    parse_arguments(skip=False)
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/loghub/cli/main.py", line 299, in parse_arguments
    show_related_issues=options.show_related_issues,
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/loghub/core/formatter.py", line 381, in create_changelog
    show_prs=show_prs)
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/loghub/core/formatter.py", line 453, in render_changelog
    show_prs=show_prs)
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 25, in top-level template code
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'pri' is undefined
```

**Comment by goanpeca** [comment]
@djhoese I tried that, but I need to have access to the repo to be able to use my token, otherwise the rate limit kicks in, any chance you could add me with write permissions, or share internally a token so I can debug this?

**Comment by goanpeca** [comment]
I will take a look again in the afternoon.

**Comment by djhoese** [comment]
I don't think you need any special permissions to the repository do you? You just need to make a personal access token on your github account. For example, I'm able to run loghub against `spyder-ide/loghub` even though I don't think I have any permissions to the repository. Note that I'm unable to reproduce the issue with the loghub repository (at least with what I've tried so far).

**Comment by djhoese** [comment]
Got it:

```
loghub spyder-ide/loghub -t "$LOGHUB_GITHUB_TOKEN" -st v0.3.0 -plg "type:bug" "Bugs fixed" -plg "reso:completed" "Features added" -plg "type:task" "Documentation changes"

LOGHUB: Querying issues since tag "v0.3.0"

Traceback (most recent call last):
  File "/home/davidh/miniconda3/envs/loghub_test/bin/loghub", line 10, in <module>
    sys.exit(main())
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/loghub/cli/main.py", line 52, in main
    parse_arguments(skip=False)
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/loghub/cli/main.py", line 299, in parse_arguments
    show_related_issues=options.show_related_issues,
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/loghub/core/formatter.py", line 381, in create_changelog
    show_prs=show_prs)
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/loghub/core/formatter.py", line 453, in render_changelog
    show_prs=show_prs)
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 25, in top-level template code
  File "/home/davidh/miniconda3/envs/loghub_test/lib/python3.7/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'pri' is undefined
```

**Comment by goanpeca** [comment]
Awesome, I will make a fix and make a release this week. Thanks for the help!
