### ISSUE TITLE
template file missing

### ISSUE THREAD

**Issue by bemcdonnell** [spyder-ide/loghub#71]
@goanpeca with Win 10, Py2.7 getting this error

```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\loghub.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\loghub\cli\main.py", line 29, in main
    parse_arguments(skip=False)
  File "c:\python27\lib\site-packages\loghub\cli\main.py", line 187, in parse_arguments
    show_prs=options.show_prs)
  File "c:\python27\lib\site-packages\loghub\core\formatter.py", line 193, in create_changelog
    show_prs=show_prs)
  File "c:\python27\lib\site-packages\loghub\core\formatter.py", line 237, in render_changelog
    with open(filepath) as f:
IOError: [Errno 2] No such file or directory: 'c:\\python27\\lib\\site-packages\\loghub\\templates\\changelog.txt'
```

**Comment by bemcdonnell** [comment]
Actually my templates folder is completely empty aside from `__init__.py`

**Comment by ccordoba12** [comment]
@goanpeca, please release 0.2.1 to fix this ASAP!

**Comment by goanpeca** [comment]
@bemcdonnell just made the release with the hotfix

**Comment by bemcdonnell** [comment]
@goanpeca It Works for me! Thanks!
