### ISSUE TITLE
Bug: No issues found for -ilg group creates error

### ISSUE THREAD

**Issue by jdetle** [spyder-ide/loghub#75]
When -ilg returns nothing then this error is thrown:
```
Traceback (most recent call last):
  File "/Users/jdetlefs/miniconda3/envs/anaconda-platform/bin/loghub", line 11, in <module>
    sys.exit(main())
  File "/Users/jdetlefs/miniconda3/envs/anaconda-platform/lib/python3.5/site-packages/loghub/cli/main.py", line 29, in main
    parse_arguments(skip=False)
  File "/Users/jdetlefs/miniconda3/envs/anaconda-platform/lib/python3.5/site-packages/loghub/cli/main.py", line 187, in parse_arguments
    show_prs=options.show_prs)
  File "/Users/jdetlefs/miniconda3/envs/anaconda-platform/lib/python3.5/site-packages/loghub/core/formatter.py", line 257, in create_changelog
    filter_issues_fixed_by_prs(filtered_issues, filtered_prs)
  File "/Users/jdetlefs/miniconda3/envs/anaconda-platform/lib/python3.5/site-packages/loghub/core/formatter.py", line 56, in filter_issues_fixed_by_prs
    for matches in pattern.finditer(body):
TypeError: expected string or bytes-like object
```
I can make a PR to try and fix this issue later today or this week.

**Comment by goanpeca** [comment]
Check with `$ loghub Anaconda-Platform/anaconda-platform --no-prs -st %(previous)s -ut %(version)s -ilg "Enhancement" "Enhancements to the platform" -ilg "Bug" "Bugs fixed" -u %(user)s -p %(password)s`
