### ISSUE TITLE
Batch processing breaks on python 3

### ISSUE THREAD

**Issue by djhoese** [spyder-ide/loghub#89]
Reversing a zip iterator in python 3 is not allowed: https://github.com/spyder-ide/loghub/blob/master/loghub/core/formatter.py#L225

Actual error when running with batch tags:

```
Traceback (most recent call last):
  File "/Users/davidh/anaconda/envs/polar2grid_py36/bin/loghub", line 11, in <module>
    sys.exit(main())
  File "/Users/davidh/anaconda/envs/polar2grid_py36/lib/python3.6/site-packages/loghub/cli/main.py", line 29, in main
    parse_arguments(skip=False)
  File "/Users/davidh/anaconda/envs/polar2grid_py36/lib/python3.6/site-packages/loghub/cli/main.py", line 187, in parse_arguments
    show_prs=options.show_prs)
  File "/Users/davidh/anaconda/envs/polar2grid_py36/lib/python3.6/site-packages/loghub/core/formatter.py", line 225, in create_changelog
    for (milestone, since_tag, until_tag) in reversed(items):
TypeError: 'zip' object is not reversible
```

Simple test in ipython:

```
In [1]: reversed(zip([1,1,1], [2,2,2]))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-ac0cda3ccbba> in <module>()
----> 1 reversed(zip([1,1,1], [2,2,2]))

TypeError: 'zip' object is not reversible
```

**Comment by djhoese** [comment]
Something like this may be a solution if you didn't want to make a list of the entire zip:

```
zip(reversed([1,2,3]), reversed([1, 2, 3]))
```

However, I have to additionally ask what the purpose is of putting the arguments in a tuple and then expanding them with the asterisk:

```
items = zip(*(milestones, empty_items, empty_items))
```

**Comment by ccordoba12** [comment]
I don't understand the logic of it. @goanpeca?

**Comment by goanpeca** [comment]
I think we need to turn it into a list... , I was just changing the order

**Comment by ccordoba12** [comment]
Yeah, and then it'd be easier to reverse it.

@davidh-ssec, could you make a PR to fix this?

**Comment by djhoese** [comment]
Will do. Thanks.
