### ISSUE TITLE
ApiNotFoundError

### ISSUE THREAD

**Issue by pydanny** [spyder-ide/loghub#94]
Environment: Python 3.6, OSX, loghub==0.3.3, installed with Pip 9.0.1

```
loghub pydanny/cookiecutter-django --since-tag 1.11.10 --until-tag v2.0.2

LOGHUB: Querying issues since tag 1.11.10 until tag v2.0.2

Traceback (most recent call last):
  File "/Users/danielgreenfeld/.virtualenvs/coursebuilder/bin/loghub", line 11, in <module>
    sys.exit(main())
  File "/Users/danielgreenfeld/.virtualenvs/coursebuilder/lib/python3.6/site-packages/loghub/cli/main.py", line 29, in main
    parse_arguments(skip=False)
  File "/Users/danielgreenfeld/.virtualenvs/coursebuilder/lib/python3.6/site-packages/loghub/cli/main.py", line 187, in parse_arguments
    show_prs=options.show_prs)
  File "/Users/danielgreenfeld/.virtualenvs/coursebuilder/lib/python3.6/site-packages/loghub/core/formatter.py", line 241, in create_changelog
    since = gh.tag(since_tag)['tagger']['date']
  File "/Users/danielgreenfeld/.virtualenvs/coursebuilder/lib/python3.6/site-packages/loghub/core/repo.py", line 170, in tag
    return self.repo('git')('tags')(sha).get()
  File "/Users/danielgreenfeld/.virtualenvs/coursebuilder/lib/python3.6/site-packages/loghub/external/github.py", line 145, in __call__
    return self._gh._http(self._method, self._path, **kw)
  File "/Users/danielgreenfeld/.virtualenvs/coursebuilder/lib/python3.6/site-packages/loghub/external/github.py", line 303, in _http
    raise ApiNotFoundError(url, req, resp)
loghub.external.github.ApiNotFoundError: https://api.github.com/repos/pydanny/cookiecutter-django/git/tags/fe7c4aa815f6fce1e9a79f3449daf232dacc175d
```

**Comment by ccordoba12** [comment]
Hey, it seems your tags are not annotated, and so they can't be obtained from the Github API:

https://developer.github.com/v3/git/tags/#tags

Nothing we can do here, except catching the exception and displaying a message about it, sorry.
